### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by JoelKanyi** [JoelKanyi/MealTime#89]

**Comment by Breens-Mbaka** [comment]
Hey @JoelKanyi would advise to use the[ Splash Screen API ](https://developer.android.com/develop/ui/views/launch/splash-screen)here, it backward compatible and you don't need an activity or fragment to render it and its quick to setup.

**Comment by JoelKanyi** [comment]
Hey thanks for the confirmation, can you work on this issue 😄

**Comment by Breens-Mbaka** [comment]
yea no worries you can assign it to me then

**Comment by Breens-Mbaka** [comment]
@JoelKanyi What was your intended look for the splash screen ? ie logo ?

**Comment by JoelKanyi** [comment]
I circle image of this:

https://github.com/JoelKanyi/MealTime/blob/development/screenshots/app_logo.png

**Comment by opeCre8tivia** [comment]
Hi guys, nice work @Breens-Mbaka  and @JoelKanyi

**Comment by JoelKanyi** [comment]
Done, thank you @Breens-Mbaka
